apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ms-demo-tekton.fullname" . }}-github-ssh-key
  labels:
    {{- include "ms-demo-tekton.labels" . | nindent 4 }}
  annotations:
    tekton.dev/git-0: github.com # Described below
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: {{ include "privateKey" . }}
  #known_hosts: {{ include "knownHosts" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ms-demo-tekton.fullname" . }}-docker-creds
  labels:
    {{- include "ms-demo-tekton.labels" . | nindent 4 }}
  annotations:
    tekton.dev/docker-0: {{ .Values.registry.url }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.registry.username }}
  password: {{ .Values.registry.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ms-demo-tekton.fullname" . }}-webhook-secret
  labels:
    {{- include "ms-demo-tekton.labels" . | nindent 4 }}
stringData:
  token: {{ .Values.github.token }}
  secret: {{ .Values.github.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ms-demo-tekton.fullname" . }}-argocd-secret
  labels:
    {{- include "ms-demo-tekton.labels" . | nindent 4 }}
stringData:
  username: {{ .Values.argocd.username }}
  password: {{ .Values.argocd.password }}
