apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{ include "ms-demo-tekton.fullname" . }}
  labels:
    {{- include "ms-demo-tekton.labels" . | nindent 4 }}
spec:
  params:
    - name: gitrevision
      description: The git revision
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
    - name: imageBaseUrl
      description: The URL/folder of the repoitory to upload the image to
    - name: argoCdUrl
      description: Argo CD server to update the tag
    - name: ArgoCdSecret
      description: Secret that holds the credentials for Argo CD
    - name: appName
      description: Name of the application to update in Argo CD
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: {{ include "ms-demo-tekton.fullname" . }}-$(uid)
        namespace: $(tt.params.namespace)
      spec:
        serviceAccountName: {{ include "ms-demo-tekton.fullname" . }}-tekton-triggers-admin
        pipelineRef:
          name: {{ include "ms-demo-tekton.fullname" . }}
        resources:
          - name: source-repo
            resourceSpec:
              type: git
              params:
              - name: revision
                value: $(tt.params.gitrevision)
              - name: url
                value: $(tt.params.gitrepositoryurl)
          - name: adService-image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: $(tt.params.imageBaseUrl)/adservice:$(tt.params.gitrevision)
          - name: cartService-image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: $(tt.params.imageBaseUrl)/cartservice:$(tt.params.gitrevision)
          - name: checkoutService-image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: $(tt.params.imageBaseUrl)/checkoutservice:$(tt.params.gitrevision)
          - name: currencyService-image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: $(tt.params.imageBaseUrl)/currencyservice:$(tt.params.gitrevision)
          - name: emailService-image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: $(tt.params.imageBaseUrl)/emailservice:$(tt.params.gitrevision)
          - name: frontendService-image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: $(tt.params.imageBaseUrl)/frontend:$(tt.params.gitrevision)
          - name: loadGenerator-image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: $(tt.params.imageBaseUrl)/loadgenerator:$(tt.params.gitrevision)
          - name: paymentService-image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: $(tt.params.imageBaseUrl)/paymentservice:$(tt.params.gitrevision)
          - name: productCatalogService-image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: $(tt.params.imageBaseUrl)/productcatalogservice:$(tt.params.gitrevision)
          - name: recommendationService-image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: $(tt.params.imageBaseUrl)/recommendationservice:$(tt.params.gitrevision)
          - name: shippingService-image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: $(tt.params.imageBaseUrl)/shippingservice:$(tt.params.gitrevision)
        params:
          - name: adServiceDockerfile
            value: ./src/adservice/Dockerfile
          - name: adServiceContext
            value: ./src/adservice
          - name: cartServiceDockerfile
            value: ./src/cartservice/Dockerfile
          - name: cartServiceContext
            value: ./src/cartservice
          - name: checkoutServiceDockerfile
            value: ./src/checkoutservice/Dockerfile
          - name: checkoutServiceContext
            value: ./src/checkoutservice
          - name: currencyServiceDockerfile
            value: ./src/currencyservice/Dockerfile
          - name: currencyServiceContext
            value: ./src/currencyservice
          - name: emailServiceDockerfile
            value: ./src/emailservice/Dockerfile
          - name: emailServiceContext
            value: ./src/emailservice
          - name: frontendServiceDockerfile
            value: ./src/frontend/Dockerfile
          - name: frontendServiceContext
            value: ./src/frontend
          - name: loadGeneratorDockerfile
            value: ./src/loadgenerator/Dockerfile
          - name: loadGeneratorContext
            value: ./src/loadgenerator
          - name: paymentServiceDockerfile
            value: ./src/paymentservice/Dockerfile
          - name: paymentServiceContext
            value: ./src/paymentservice
          - name: productCatalogServiceDockerfile
            value: ./src/productcatalogservice/Dockerfile
          - name: productCatalogServiceContext
            value: ./src/productcatalogservice
          - name: recommendationServiceDockerfile
            value: ./src/recommendationservice/Dockerfile
          - name: recommendationServiceContext
            value: ./src/recommendationservice
          - name: shippingServiceDockerfile
            value: ./src/shippingservice/Dockerfile
          - name: shippingServiceContext
            value: ./src/shippingservice
          - name: argoCdUrl
            value: $(tt.params.argoCdUrl)
          - name: ArgoCdSecret
            value: $(tt.params.ArgoCdSecret)
          - name: commitId
            value: $(tt.params.gitrevision)
          - name: appName
            value: $(tt.params.appName)
---
